export default {
  // generators
  componentMessage: 'This component is generated by the generator',
  welcome: 'Welcome to use generator to generate your file',

  // LoginScene
  loginScene: 'Login',
  submit: 'Submit',
  placeholderEmail: 'Please enter your email',
  placeholderPassword: 'Please enter your password',
  email: 'Email',

  // HomeScene
  homeScene: 'Home Scene',
  login: 'Go to Login!',
  vi: 'Vietnamese',
  en: 'English',
  add: 'Add',
  minus: 'Minus',

  // AppFooter
  footer: 'react-native-boilerplate',

  // AppHeader
  back: 'Back',

  // Validate Message
  required: 'This is a required field',
  isEmail: 'Incorrect email format',
  minLength: 'Minimum of',
  characters: 'characters',
  confirmation: 'Password and password confirmation must be the same',

  firstName: 'First Name*',
  lastName: 'Last Name*',
  emailAddress: 'Email Address*',
  phoneNumber: 'Phone Number*',
  address: 'Address*',
  password: 'Password*',

  //homePublic
  setting: 'Settings',
  signOut: 'Sign Out',
  result: 'Result',
  filter: 'Filter',
  myAccount: 'My Account',
  editAccount: 'Edit Account',

  //editProfileForm
  username: 'Username',
  gender: 'Gender',
  genderPlaceholder: 'Set gender',
  birthday: 'Birthday',
  phoneNumberEdit: 'Phone Number',
  emailEdit: 'Email Address',
  enterOldPass: 'Change password',
  enterNewPass: 'Enter your new password',
  saveChange: 'Save Change',
  addNewAddress: 'Add a new address',
  editAddress: 'Edit Address',
  newAddress: 'New Address',

  //editAddressForm
  name: 'Name',
  city: 'City',
  district: 'District',
  localAddress: 'Local Address',
  postCode: 'Post Code',
  country: 'Country',
  deleteAddress: 'Delete Address',
  save: 'Save',
};
